### ISSUE TITLE
Icons from Iconize don't appear in FileTreeAlternative

### ISSUE THREAD

**Issue by mlevison** [ozntel/file-tree-alternative#176] opened 2023-11-16 02:22 UTC
Not sure where to ask for help/fix. Iconize makes my vault look nice. 

FiletreeAlternative makes my folders behave like a sensible finder. How could we tweak filetree to pay attention to the icons from Iconize?

**Comment by jvdevlab** [comment] 2023-12-30 20:17
+1 This would be great. I use Iconezer rules to place icons on folder automatically along with your plugin this helps navigating large folder trees.

**Comment by jvdevlab** [comment] 2023-12-30 20:39
This is actually a dupe of https://github.com/ozntel/file-tree-alternative/issues/109 which has more upvotes.

**Closed** 2023-12-30 20:48 UTC
