### ISSUE TITLE
Installed latest on 15.2 and made come other commands disappear

### ISSUE THREAD

**Issue by pcause** [ozntel/file-tree-alternative#97] opened 2022-06-27 13:25 UTC
I installed the latest and after that when I hit ctrl-p some commands were not in the list.  Disabled and they appeared.  re-enabled and commands are back again

**Comment by ozntel** [comment] 2022-08-28 09:25
The plugin doesn't interfere with any other commands. I am not sure if it is caused by this plugin. Is it still the same?

**Comment by ozntel** [comment] 2022-12-25 14:01
I am closing this issue but let me know if the issue persists. Thanks

**Closed by ozntel** 2022-12-25 14:01 UTC
